README.md, main.go
=> Issue 3.dockter.2

CHANGELOG.md, g2config/g2config_impl.go, g2configmgr/g2configmgr_impl.go, g2configmgr/g2configmgr_test.go, g2diagnostic/g2diagnostic_impl.go, g2diagnostic/g2diagnostic_test.go, g2engine/g2engine_impl.go, g2engine/g2engine_test.go, g2product/g2product_impl.go, main.go
=> #19 Added code to support goroutines

g2configmgr/g2configmgr_test.go, g2diagnostic/g2diagnostic_test.go, g2engine/g2engine_test.go, go.mod, go.sum, main.go
=> #24 Fix cyclomatic and ineffectual assigns

Makefile, g2config/g2config.c, g2config/g2config_impl.go, g2config/g2config_test.go, g2configmgr/g2configmgr.c, g2configmgr/g2configmgr_impl.go, g2configmgr/g2configmgr_test.go, g2diagnostic/g2diagnostic.c, g2diagnostic/g2diagnostic_impl.go, g2diagnostic/g2diagnostic_test.go, g2engine/g2engine.c, g2engine/g2engine_impl.go, g2product/g2product.c, g2product/g2product_impl.go, g2product/g2product_test.go
=> #24 Savepoint

g2diagnostic/g2diagnostic_impl.go
Issue number: #35 
success was considered failure
basic functionality
=> #35 fix bug in FetchNextEntityBySize

.github/workflows/go-proxy-pull.yaml, Makefile, g2configmgr/g2configmgr_test.go, g2configmgr/main.go, g2diagnostic/g2diagnostic_test.go, g2diagnostic/main.go, g2engine/g2engine_test.go, g2engine/main.go, g2product/main.go, main.go
=> Issue 38.dockter.2

CHANGELOG.md, Makefile, g2diagnostic/g2diagnostic_impl.go
=> #38 Prepare for versioned release

.github/workflows/go-proxy-pull.yaml
=> #42 Fix parameter in GitAction

CHANGELOG.md, g2api/main.go, g2config/main.go, g2configmgr/main.go, g2diagnostic/main.go, g2engine/main.go, g2product/main.go
=> #45 Simplify GetSdkId()

.github/workflows/make-go-tag.yaml
=> #48 Add make-go-tag.yaml

CHANGELOG.md, g2error/g2error.go, g2error/g2error_test.go
=> Issue 55.dockter.1

CHANGELOG.md
=> #62 Prepare for versioned release

CHANGELOG.md
=> #64 Fix CHANGELOG

.github/workflows/go-test.yaml, go.mod
=> Issue 63.dockter.2

.github/workflows/dependabot-automation.yaml
=> #83 Add shared dependabot automation workflow

g2config/main.go, g2configmgr/main.go, g2diagnostic/main.go, g2engine/main.go, g2product/main.go
=> #87 Updated message

.github/workflows/go-test-linux.yaml, .github/workflows/go-test-windows.yaml, .gitignore, Makefile, go.mod, go.sum
=> #93 Add windows testing

.gitignore, CHANGELOG.md
=> #95 Prepare for versioned release

CHANGELOG.md, g2api/main.go
=> #95 Remove obsolete methods

.github/workflows/go-proxy-pull.yaml, .gitignore, .project, README.md, doc.go, go.mod
=> #114 Prepare for versioned release

.github/workflows/go-proxy-pull.yaml, .github/workflows/go-test-darwin.yaml, .github/workflows/go-test-linux.yaml, .github/workflows/go-test-windows.yaml, .github/workflows/gofmt.yaml, .github/workflows/gosec.yaml, .github/workflows/make-go-tag.yaml
=> #114 update go workflow permissions

.github/workflows/go-test-linux.yaml, .github/workflows/go-test-windows.yaml, CHANGELOG.md, CONTRIBUTING.md, README.md
Issue number: senzing-factory/build-resources#144
=> senzing-factory/build-resources#144 cleanup

senzing/senzing_test.go
=> #185 Fix SZ_FIND_PATH_PREFER_EXCLUDE

CHANGELOG.md, senzing/flags.go, senzing/senzing_test.go
=> #217 Fix flag name

CHANGELOG.md, senzing/main.go
=> #234 Add SzAbstractFactory.Close()
